### ISSUE TITLE
Plan to update for Spring Boot 3

### ISSUE THREAD

**Issue by hamidsafdari** [leangen/graphql-spqr-spring-boot-starter#125]
Hi,

Are there are any plans to update this library for Spring Boot 3? It looks like a lot have changed with the new version of Spring Boot. For example, the minimum Java version is 17, javax support has been removed and jakarta libraries have replaced them and there are breaking changes with how security is configured. Many dependencies have also been updated to their most recent versions.

Trying to upgrade a project to Spring Boot 3 with `graphql-spqr-spring-boot-starter` as a dependency seems like a no-go for the moment. It also takes considerable effort for a project that heavily depends on this library to use a different solution like Spring GraphQL or GraphQL Java. Please correct me if I've got that wrong.

It's also true that updating this library to accommodate for those changes will mean that the projects depending on older versions of Spring Boot cannot benefit from bug fixes and improvements. Perhaps this library could finally graduate to a major version, or maybe a branch could hold the 0.0.6 improvements.

**Comment by kaqqao** [comment]
The just released version 0.0.7 will likely be the last version based on Spring Boot 2. But also likely the last version of this starter in its current form. When I first made this project, there was nothing in Spring to support GraphQL. So this starter had to implement all the network/infrastructure level stuff on its own (e.g. implement the de facto standard GraphQL-over-HTTP/WS/SSE etc specifications, across Spring's MVC and WebFlux stacks). This is a ton of work to maintain, chasing each version of Spring Boot and graphql-java, that no longer makes sense. For these reasons, going forward, I'll rebase the project onto Spring GraphQL, benefitting from all the development on that project instead of playing catch-up with it. This will be a major breaking change unfortunately, as many SPQR's extension points will be replaced with Spring GraphQL's equivalents. But it will leave this project in a much healthier shape. And since I don't foresee  _too much_ migration pain for the end-user, I think this is more than worth it.

**Comment by EronAlves1996** [comment]
Actually, I'm playing around with 0.0.7 release with spring boot 3.0.0, is likely working right now, going with some few bugs to launch GraphiQL, requiring obligatory configuration. I'll see the cause for this and open an issue.

**Comment by mdtamim** [comment]
@kaqqao when are you planning to release spqr with support for Java 17 and Spring boot 3?We  are planning to migrate to Spring boot 3 asap as all spring web 5.x.x versions are impacted by vulnerability to Remote Code Execution https://mvnrepository.com/artifact/org.springframework/spring-web) .

**Comment by ErtugrulSener** [comment]
The update to Spring Boot 3 has been done already, a new version "1.0.0" will be released soon. See here for more details: https://github.com/leangen/graphql-spqr-spring-boot-starter/issues/133

I think we should create a new issue for the Spring GraphQL Startet stuff (which was mentioned above but in my point of view: It's out of scope for this issue).,

**Comment by kaqqao** [comment]
v1.0.0 is out
